import unittest

from shared import Orientation, dijkstra_with_path
from simulator import Road, Simulator
from simulator.car import Car
from simulator.path import Path
from simulator.stop_junction import StopJunction


class TestStopJunction(unittest.TestCase):

    def test_a_car_should_leave_priority_when_it_is_at_a_stop_and_there_is_another_car_on_the_right(self):
        simulator = Simulator()
        stop = StopJunction(simulator, {Orientation.NORTH: (0, 1), Orientation.EAST: (1, 0),
                                      Orientation.SOUTH: (1, 0), Orientation.WEST: (0, 1)}, Orientation.WEST)
        r1 = Road(simulator, 1, Orientation.NORTH, 1)
        r2 = Road(simulator, 1, Orientation.WEST, 1)
        r3 = Road(simulator, 1, Orientation.WEST, 1)
        r1.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], r3.nodes[0][0]]), r1.nodes[0][0], 0)
        r2.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], r3.nodes[0][0]]), r2.nodes[0][0], 0)

        stop.add_predecessor(Orientation.NORTH, r1)
        stop.add_predecessor(Orientation.WEST, r2)
        r3.add_predecessor(Orientation.WEST, stop)

        self.assertIsNotNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(r3.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNone(r2.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)


    def test_a_car_should_leave_priority_when_it_is_at_a_stop_and_there_is_another_car_on_the_left(self):
        simulator = Simulator()
        stop = StopJunction(simulator, {Orientation.NORTH: (0, 1), Orientation.EAST: (0, 1),
                                      Orientation.SOUTH: (1, 0), Orientation.WEST: (1, 0)}, Orientation.EAST)
        r1 = Road(simulator, 1, Orientation.NORTH, 1)
        r2 = Road(simulator, 1, Orientation.EAST, 1)
        r3 = Road(simulator, 1, Orientation.EAST, 1)
        r1.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], r3.nodes[0][0]]), r1.nodes[0][0], 0)
        r2.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], r3.nodes[0][0]]), r2.nodes[0][0], 0)

        stop.add_predecessor(Orientation.NORTH, r1)
        stop.add_predecessor(Orientation.EAST, r2)
        r3.add_predecessor(Orientation.EAST, stop)

        self.assertIsNotNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(r3.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNone(r2.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)

    def test_a_car_should_leave_priority_when_it_is_at_a_stop_and_there_are_another_cars_on_the_left_and_on_the_right(self):
        simulator = Simulator()
        stop = StopJunction(simulator, {Orientation.NORTH: (1, 0), Orientation.EAST: (0, 1),
                                      Orientation.SOUTH: (1, 0), Orientation.WEST: (1, 0)}, Orientation.WEST)
        r1 = Road(simulator, 1, Orientation.NORTH, 1)
        r2 = Road(simulator, 1, Orientation.EAST, 1)
        r3 = Road(simulator, 1, Orientation.SOUTH, 1)
        r4 = Road(simulator, 1, Orientation.EAST, 1)

        r1.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], r4.nodes[0][0]]), r1.nodes[0][0], 0)
        r2.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], r4.nodes[0][0]]), r2.nodes[0][0], 0)
        r3.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], r4.nodes[0][0]]), r3.nodes[0][0], 0)

        stop.add_predecessor(Orientation.NORTH, r1)
        stop.add_predecessor(Orientation.EAST, r2)
        stop.add_predecessor(Orientation.SOUTH, r3)
        r4.add_predecessor(Orientation.EAST, stop)

        self.assertIsNotNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNotNone(r3.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r4.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNotNone(r3.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r4.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNotNone(r3.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(r4.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r4.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNotNone(r2.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(r4.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(r1.nodes[0][0].current_car)
        self.assertIsNone(r2.nodes[0][0].current_car)
        self.assertIsNone(r3.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(r4.nodes[0][0].current_car)

    def test_a_car_should_leave_priority_when_there_is_opposite_ways_it_is_at_a_stop_and_there_are_another_cars_on_the_left_and_on_the_right_and_with_uturn(
            self):
        simulator = Simulator()
        stop = StopJunction(simulator, {Orientation.NORTH: (1, 1), Orientation.EAST: (1, 1),
                                        Orientation.SOUTH: (1, 1), Orientation.WEST: (1, 1)}, Orientation.WEST)
        in_N = Road(simulator, 1, Orientation.NORTH, 1)
        in_E = Road(simulator, 1, Orientation.EAST, 1)
        in_S = Road(simulator, 1, Orientation.SOUTH, 1)
        out_S = Road(simulator, 1, Orientation.SOUTH, 1)
        out_W = Road(simulator, 1, Orientation.WEST, 1)
        out_N = Road(simulator, 1, Orientation.NORTH, 1)

        stop.add_predecessor(Orientation.NORTH, in_N)
        stop.add_predecessor(Orientation.EAST, in_E)
        stop.add_predecessor(Orientation.SOUTH, in_S)
        out_S.add_predecessor(Orientation.SOUTH, stop)
        out_W.add_predecessor(Orientation.WEST, stop)
        out_N.add_predecessor(Orientation.NORTH, stop)

        in_N.nodes[0][0].current_car = Car(Path(dijkstra_with_path(simulator.get_nodes(), simulator.weights, in_N.nodes[0][0], out_S.nodes[0][0])), in_N.nodes[0][0], 0)
        in_E.nodes[0][0].current_car = Car(Path(dijkstra_with_path(simulator.get_nodes(), simulator.weights, in_E.nodes[0][0], out_W.nodes[0][0])), in_E.nodes[0][0], 0)
        in_S.nodes[0][0].current_car = Car(Path(dijkstra_with_path(simulator.get_nodes(), simulator.weights, in_S.nodes[0][0], out_N.nodes[0][0])), in_S.nodes[0][0], 0)

        self.assertIsNotNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][1].current_car)
        self.assertIsNotNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNotNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][1].current_car)
        self.assertIsNotNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNotNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNotNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNotNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNotNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNotNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNotNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

    def test_a_car_should_leave_priority_when_there_is_opposite_ways_it_is_at_a_stop_and_there_are_another_cars_on_the_left_and_on_the_right(
            self):
        simulator = Simulator()
        stop = StopJunction(simulator, {Orientation.NORTH: (1, 1), Orientation.EAST: (1, 1),
                                        Orientation.SOUTH: (1, 1), Orientation.WEST: (1, 1)}, Orientation.WEST)
        in_N = Road(simulator, 1, Orientation.NORTH, 1)
        in_E = Road(simulator, 1, Orientation.EAST, 1)
        in_S = Road(simulator, 1, Orientation.SOUTH, 1)
        out_S = Road(simulator, 1, Orientation.SOUTH, 1)
        out_W = Road(simulator, 1, Orientation.WEST, 1)
        out_N = Road(simulator, 1, Orientation.NORTH, 1)

        stop.add_predecessor(Orientation.NORTH, in_N)
        stop.add_predecessor(Orientation.EAST, in_E)
        stop.add_predecessor(Orientation.SOUTH, in_S)
        out_S.add_predecessor(Orientation.SOUTH, stop)
        out_W.add_predecessor(Orientation.WEST, stop)
        out_N.add_predecessor(Orientation.NORTH, stop)

        in_N.nodes[0][0].current_car = Car(
            Path(dijkstra_with_path(simulator.get_nodes(), simulator.weights, in_N.nodes[0][0], out_W.nodes[0][0])), in_N.nodes[0][0], 0)
        in_E.nodes[0][0].current_car = Car(
            Path(dijkstra_with_path(simulator.get_nodes(), simulator.weights, in_E.nodes[0][0], out_N.nodes[0][0])), in_E.nodes[0][0], 0)
        in_S.nodes[0][0].current_car = Car(
            Path(dijkstra_with_path(simulator.get_nodes(), simulator.weights, in_S.nodes[0][0], out_S.nodes[0][0])), in_S.nodes[0][0], 0)

        self.assertIsNotNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][1].current_car)
        self.assertIsNotNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNotNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNotNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNotNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNotNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNotNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_N.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_E.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][1].current_car)
        self.assertIsNone(stop.nodes[1][0].current_car)
        self.assertIsNone(stop.nodes[1][1].current_car)
        self.assertIsNone(out_S.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNotNone(out_N.nodes[0][0].current_car)

    def test_stop_should_be_respected_when_there_are_2_entries_and_2_exits_and_cars_go_in_the_same_direction(self):
        simulator = Simulator()
        stop = StopJunction(simulator, {Orientation.NORTH: (1, 0), Orientation.EAST: (0, 1),
                                        Orientation.SOUTH: (1, 0), Orientation.WEST: (0, 1)}, Orientation.NORTH)
        in_N = Road(simulator, 1, Orientation.NORTH, 1)
        in_S = Road(simulator, 1, Orientation.SOUTH, 1)
        out_E = Road(simulator, 1, Orientation.EAST, 1)
        out_W = Road(simulator, 1, Orientation.WEST, 1)

        stop.add_predecessor(Orientation.NORTH, in_N)
        stop.add_predecessor(Orientation.SOUTH, in_S)
        out_E.add_predecessor(Orientation.EAST, stop)
        out_W.add_predecessor(Orientation.WEST, stop)

        in_N.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], out_W.nodes[0][0]]), in_N.nodes[0][0], 0)
        in_S.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], out_W.nodes[0][0]]), in_N.nodes[0][0], 0)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

    def test_stop_should_be_respected_when_there_are_2_entries_and_2_exits_and_cars_go_in_different_directions(self):
        simulator = Simulator()
        stop = StopJunction(simulator, {Orientation.NORTH: (1, 0), Orientation.EAST: (0, 1),
                                        Orientation.SOUTH: (1, 0), Orientation.WEST: (0, 1)}, Orientation.NORTH)
        in_N = Road(simulator, 1, Orientation.NORTH, 1)
        in_S = Road(simulator, 1, Orientation.SOUTH, 1)
        out_E = Road(simulator, 1, Orientation.EAST, 1)
        out_W = Road(simulator, 1, Orientation.WEST, 1)

        stop.add_predecessor(Orientation.NORTH, in_N)
        stop.add_predecessor(Orientation.SOUTH, in_S)
        out_E.add_predecessor(Orientation.EAST, stop)
        out_W.add_predecessor(Orientation.WEST, stop)

        in_N.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], out_W.nodes[0][0]]), in_N.nodes[0][0], 0)
        in_S.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], out_E.nodes[0][0]]), in_N.nodes[0][0], 0)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNotNone(out_E.nodes[0][0].current_car)

        simulator.tick()

        in_N.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], out_E.nodes[0][0]]), in_N.nodes[0][0], 0)
        in_S.nodes[0][0].current_car = Car(Path([stop.nodes[0][0], out_W.nodes[0][0]]), in_N.nodes[0][0], 0)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNotNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNotNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNotNone(stop.nodes[0][0].current_car)
        self.assertIsNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)

        simulator.tick()
        self.assertIsNone(in_N.nodes[0][0].current_car)
        self.assertIsNone(in_S.nodes[0][0].current_car)
        self.assertIsNone(stop.nodes[0][0].current_car)
        self.assertIsNotNone(out_W.nodes[0][0].current_car)
        self.assertIsNone(out_E.nodes[0][0].current_car)
